modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-forestbiomesdimension/issues"
license = "ARR"

[[mods]]
modId = "forestbiomesdimension"
version = "${version}"
displayName = "Forest Biomes Dimension"
authors = "mahmudindev"
description = '''
Add forest biomes as separate dimension.
'''
logoFile = "assets/forestbiomesdimension/icon.png"

[[dependencies.forestbiomesdimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forestbiomesdimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forestbiomesdimension]]
modId = "modifiedbiomesource"
type = "required"
versionRange = "[0.0.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.forestbiomesdimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.forestbiomesdimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "forestbiomesdimension.mixins.json"
